// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'dext.let', kind: "module", path: './dext/let.html', attributes: []},
{name: 'dext.let.let', kind: "functiondeclaration", path: './dext/let/let.html', attributes: ["auto"]},
{name: 'dext.record', kind: "module", path: './dext/record.html', attributes: []},
{name: 'dext.record.Record', kind: "structdeclaration", path: './dext/record/Record.html', attributes: []},
{name: 'dext.record.Record.deconstruct', kind: "functiondeclaration", path: './dext/record/Record.deconstruct.html', attributes: ["const"]},
{name: 'dext.record.Record.isType', kind: "enummemberdeclaration", path: './dext/record/Record.isType.html', attributes: []},
{name: 'dext.record.Record.opEquals', kind: "functiondeclaration", path: './dext/record/Record.opEquals.html', attributes: ["const", "nothrow", "trusted"]},
{name: 'dext.record.Record.pointerTo', kind: "functiondeclaration", path: './dext/record/Record.pointerTo.html', attributes: ["auto", "const", "nothrow", "trusted"]},
{name: 'dext.record.Record.Self', kind: "aliasdeclaration", path: './dext/record/Record.Self.html', attributes: []},
{name: 'dext.record.Record.this', kind: "functiondeclaration", path: './dext/record/Record.this.html', attributes: []},
{name: 'dext.record.Record.toHash', kind: "functiondeclaration", path: './dext/record/Record.toHash.html', attributes: ["const", "nothrow", "trusted"]},
{name: 'dext.record.Record.toPointer', kind: "aliasdeclaration", path: './dext/record/Record.toPointer.html', attributes: []},
{name: 'dext.record.Record.toString', kind: "functiondeclaration", path: './dext/record/Record.toString.html', attributes: ["const"]},
{name: 'dext.record.Record.Types', kind: "aliasdeclaration", path: './dext/record/Record.Types.html', attributes: []},
{name: 'dext.record.Record._fieldNames', kind: "variabledeclaration", path: './dext/record/Record._fieldNames.html', attributes: []},
{name: 'dext', kind: "module", path: './dext.html', attributes: []},
];
